### ISSUE TITLE
Too few arguments to function Aoe\Restler\System\RestlerBuilderAware::__construct(), 0 passed

### ISSUE THREAD

**Issue by infabo** [AOEpeople/TYPO3_Restler#71]
Starting with version 10.2.0 the following error occurs:

![image](https://user-images.githubusercontent.com/3999104/146015156-7189689d-0dfb-4d37-8ef2-d544b029e0f7.png)

Basically it is just this config:

```yaml
routeEnhancers:
    RestlerEnhancer:
        type: Restler
        default: '.json'
```
